### ISSUE TITLE
Code to reproduce experiments?

### ISSUE THREAD

**Issue by neubig** [NL2Code/CodeR#3]
Wow, congratulations on the great results on SWE-Bench Lite! We would love to reproduce the results, are there plans to release the code?

**Comment by john-b-yang** [comment]
Second this! Congrats as well on the strong performance!

**Comment by neubig** [comment]
This is probably not relevant anymore given that there are better options, so I'm going to close this issue.

**Comment by Fs2qFtoS** [comment]
so, which one is better option

**Comment by neubig** [comment]
You can look at the open-source options on the SWE-Bench leaderboard: https://www.swebench.com/

Currently [OpenHands](https://github.com/All-Hands-AI/OpenHands) is the highest-scoring (caveat - I'm an author of OpenHands).

**Comment by Fs2qFtoS** [comment]
Thanks a lot on that and congratulation!

> You can look at the open-source options on the SWE-Bench leaderboard: https://www.swebench.com/
> 
> Currently [OpenHands](https://github.com/All-Hands-AI/OpenHands) is the highest-scoring (caveat - I'm an author of OpenHands).

**Comment by ghLcd9dG** [comment]
> Thanks a lot on that and congratulation!
> 
> > You can look at the open-source options on the SWE-Bench leaderboard: https://www.swebench.com/
> > Currently [OpenHands](https://github.com/All-Hands-AI/OpenHands) is the highest-scoring (caveat - I'm an author of OpenHands).

Ohhhhhh, bro, it's you. Just a few days ago, I was thinking of sending you a letter, but I hesitated because you're such a renowned and accomplished researcher.
