### ISSUE TITLE
Does PlanD use ground truth tests?

### ISSUE THREAD

**Issue by zkx06111** [NL2Code/CodeR#4]
Hi, does the plan D mentioned in your paper use "fail-to-pass" tests that are actually used to evaluate the patches?

If so, this would be kind of unfair because most of the other methods do not use those.

Could you maybe specify how many instances in the paper are solved by Plan D?

**Comment by NL2Code** [comment]
Hi, please refer to the Issue #2. We will update our arXiv to make this point clear. More details such as logs, results, and trajs can be found in this repo.

Thank your for your questions.
