### ISSUE TITLE
Which multi-agent framework and LLM did you use exactly?

### ISSUE THREAD

**Issue by Slach** [NL2Code/CodeR#6]
Is this not clear from paper
Are you going to publish it?

**Comment by NL2Code** [comment]
Hi, @Slach, we implement CodeR with multi-agent based on [the SWE-agent code](https://github.com/princeton-nlp/SWE-agent), and do not use other framework. The LLM used in CodeR is `GPT 4 preview-1106` as we have already stated in [Section 4.1.1 of our paper](https://arxiv.org/pdf/2406.01304). For your second question, we will continue to refine CodeR and decide whether to publish as appropriate.
